### ISSUE TITLE
create action NoMethodError: undefined method `join' for #<string

### ISSUE THREAD

**Issue by c1505** [learn-co-curriculum/playlister-sinatra#43]
Not sure what I am doing to cause this that hasn't happened with other people.  Happened in my tests and also when running the app locally.      

It was fixed by adding this to my gemfile: 
gem 'sinatra-fix_951', require: 'sinatra/fix_951'

Was able to re-create the issue by commenting the above line in my gemfile.  

It is fixed in newer versions of sinatra as well.  
The issues thread on the problem in sinatra is here https://github.com/sinatra/sinatra/issues/951 .

**Comment by aviflombaum** [comment]
Hi @c1505 - that's right, I've addressed this in https://github.com/learn-co-curriculum/playlister-sinatra/commit/d0d4b4d8d07b88842f6e30c099702a02739debda

@StevenNunez @jmburges what do you all think of not including Gemfile.lock so that students get their own latest versions of gems and avoiding these issues? If we need a particular version it should be locked in Gemfile not Gemfile.lock. I think we should programmatically delete every gemfile.lock from our curriculum.

cc @AnnJohn - How do we redeploy this?

**Comment by AnnJohn** [comment]
redeployed, closing issue. 

but gemfile.lock is still in solution branch
