### ISSUE TITLE
unsure of issues

### ISSUE THREAD

**Issue by ritchey0713** [learn-co-curriculum/playlister-sinatra#65]
had several issues, even after using solution? could not get all tests to pass properly?

**Comment by DanielSeehausen** [comment]
Hi @ritchey0713 

We just ironed out some dependency versioning, which perhaps your issue was related to?

If you are still having trouble, we would certainly appreciate additional feedback:

Would you mind providing a bit more detail about the issue? Things that are especially useful:

An expanded explanation of what's going on.
Steps to reproduce the issue.
Details about your environment.
What's your operating system? Which version?
Are you using the Learn IDE or a local development environment?
A stack trace of any errors.
Thanks! 💙
