### ISSUE TITLE
Sinatra Playlister lab issues

### ISSUE THREAD

**Issue by RoUchiha** [learn-co-curriculum/playlister-sinatra#86]
### Canvas Link

https://learning.flatironschool.com/courses/1880/assignments/125480?module_item_id=259355

### Concern

Cannot pass the 4th or 5th spec tests. Even tried pasting everything from the solution branch into the lab and still not a single passing test. Been struggling with this for days now and it's insanely annoying that I have wasted so much time.

**Comment by lizbur10** [comment]
Hi @RoUchiha ! Thanks for raising this issue. 

I was not able to reproduce the problem - the tests are passing for me. The issue may be with your code or your environment setup rather than with the lesson itself or the instructions. The curriculum team monitors these issues so that we can fix typos and bugs in the curriculum, but we aren't equipped to provide support.

To get help with your question, you should either: 

- Reach out to your instructor, or
- Use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team

Please re-open this issue if you believe the lesson needs to be updated.

Hope you are able to get this resolved!
